behaviors:
  CarDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.1
        use_actions: true
        demo_path: Demos/TraversingFinal_0.demo
    behavioral_cloning:
      demo_path: Demos/TraversingFinal_0.demo
      strength: 0.5
      steps: 200000
    max_steps: 1000000
    checkpoint_interval: 500000
    time_horizon: 64
    summary_freq: 10000